# Generated by Django 5.1.7 on 2025-03-20 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.CharField(default='', max_length=400)),
                ('carColor', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CarNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstLetter', models.CharField(max_length=1)),
                ('secondLetter', models.CharField(max_length=1)),
                ('thirdLetter', models.CharField(blank=True, max_length=1)),
                ('firstNo', models.IntegerField(max_length=1)),
                ('secondNo', models.IntegerField(max_length=1)),
                ('thirdNo', models.IntegerField(max_length=1)),
                ('fourthNo', models.IntegerField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CarEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entranceTime', models.DateTimeField(auto_now_add=True)),
                ('carID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.car')),
                ('securityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exitTime', models.DateTimeField(auto_now_add=True)),
                ('carID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.car')),
                ('securityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.car')),
                ('hostID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
