# Generated by Django 5.1.7 on 2025-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
