# Generated by Django 5.1.7 on 2025-03-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_blacklist_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carNo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='car.carno'),
        ),
    ]
