# Generated by Django 5.1.7 on 2025-03-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carno',
            name='firstNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carno',
            name='fourthNo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='carno',
            name='secondNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carno',
            name='thirdNo',
            field=models.IntegerField(),
        ),
    ]
