# Generated by Django 5.1.7 on 2025-03-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_carno_firstno_alter_carno_fourthno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carno',
            name='firstNo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='carno',
            name='fourthNo',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='carno',
            name='secondNo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='carno',
            name='thirdNo',
            field=models.CharField(max_length=1),
        ),
    ]
