# Generated by Django 5.1.7 on 2025-04-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_car_createdby_alter_car_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='userID',
            new_name='user',
        ),
    ]
