# Generated by Django 5.1.7 on 2025-04-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_rename_carid_blacklist_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carentrance',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carentrance',
            old_name='securityID',
            new_name='security',
        ),
        migrations.RenameField(
            model_name='carexit',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carexit',
            old_name='securityID',
            new_name='security',
        ),
    ]
