# Generated by Django 5.2 on 2025-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_rename_carid_carentrance_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carno',
            name='fourthNo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='carno',
            name='thirdLetter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
