# Generated by Django 5.1.7 on 2025-04-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='profile-image/', width_field='image_width'),
        ),
    ]
