# Generated by Django 5.1.7 on 2025-04-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('security', 'Security'), ('carHolder', 'Carholder')], max_length=50),
        ),
    ]
